import Footer from "@/components/common/footer/footer";
import Navbar from "@/components/common/navbar/navbar";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "reaDRadar | Books",
  description: "Generated by create next app",
};
export default function BookLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Navbar />
      <div className="flex flex-col gap-6 w-4/5 mx-auto  py-24 book-container">
        {children}
      </div>
      <Footer />
    </>
  );
}
