
import ProvidersWrapper from "@/context/wrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Suspense } from "react";
import { Spin } from "antd";
import Head from "@/components/common/head/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book recommendation System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Head/>
      <ProvidersWrapper>
        <body className={["h-full w-full", inter.className].join(" ")}>
          <Suspense
            fallback={
              <Spin tip="Loading" size="large">
                <div className="content" />
              </Spin>
            }
          >
            {children}
          </Suspense>
        </body>
      </ProvidersWrapper>
    </html>
  );
}
