import ProvidersWrapper from "@/context/wrapper";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Book recommendation System",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ProvidersWrapper>
        <body className={["h-full w-full", inter.className].join(" ")}>
          {children}
        </body>
      </ProvidersWrapper>
    </html>
  );
}
